apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: order-service
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: order-service
    release: {{ .Release.Name }}
