name: order-service
version: 0.1.0

# Application configuration
replicaCount: 2
image:
  repository: orderserviceregistry.azurecr.io/order-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

nodeSelector: {}

affinity: {}

tolerations: []

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths: 
        - path: /
          pathType: Prefix
  tls: []

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  
# Liveness and readiness probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  httpGet:
    path: /health
    port: http

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
  httpGet:
    path: /health
    port: http
