name: order-service
version: 0.1.0

# Application configuration
replicaCount: 2
image:
  repository: ""
  tag: ""
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Network Policy Configuration
networkPolicy:
  enabled: true
  ingress:
    - from:
      - podSelector: {}
      ports:
      - protocol: TCP
        port: 8080
  egress:
    - to:
      - podSelector: {}
      ports:
      - protocol: TCP
        port: 8080
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

nodeSelector: {}

affinity: {}

tolerations: []

# Ingress configuration
ingress:
  enabled: true
  ingressClass: nginx
  host: localhost
  annotations: {}
  paths:
    - path: /

# Service configuration
# Liveness and readiness probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  httpGet:
    path: /health
    port: http

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

# Additional configuration
  port: http
